config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: destdb
      host: 0.0.0.0
      pass: StrongPassw0rd
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: prod
